"""001 add film model

Revision ID: 4812a36e8afd
Revises: 
Create Date: 2025-01-02 06:02:45.269178

"""
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4812a36e8afd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    table = op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_films_year'), ['year'], unique=False)
    op.bulk_insert(table, [
        {
            "title": "The Matrix",
            "year": 1999,
            "uuid": str(uuid.uuid4()),
        },
        {
            "title": "The Matrix Reloaded",
            "year": 2003,
            "uuid": str(uuid.uuid4()),
        },
        {
            "title": "The Matrix Revolutions",
            "year": 2003,
            "uuid": str(uuid.uuid4()),
        },
        {
            "title": "The Animatrix",
            "year": 2003,
            "uuid": str(uuid.uuid4()),
        },
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_films_year'))

    op.drop_table('films')
    # ### end Alembic commands ###
